### PR TITLE
added support for KL400 smart light strip

### PR DESCRIPTION
**Pull request by bcwood**

### CODE REVIEW

**Comment by anthturner** [comment]
Hey, thanks for the contribution!

As I don't have this product, can I safely assume you have tested to make sure it works?

If so I think we can bring this in and release a new NuGet package too.

**Comment by bcwood** [comment]
Yes I do, and this has worked great! In theory you can address each LED in
the light strip individually, and control the color of each separately, so
eventually I would like to enhance this to add that functionality. But for
the time being, this has worked great to address my immediate use case.

**Comment by anthturner** [comment]
Cool! If you have any docs on how to individually address LEDs, I can take a crack at it in my spare time. If I do, I'll keep an active public branch with the changes.

Glad you're able to find this library useful!

**Review by anthturner — APPROVED** [review]

**Comment by anthturner** [comment]
Note for future: I plan to release a new NuGet version shortly, but I want to put a tiny bit of time in to refactoring a couple pieces of this code that I cringe at when I browse this repo.

(Should be within the next week, though)

**Comment by bcwood** [comment]
I don't have any docs on how to individually address LEDs, I just know that in the app, they have some presets with varying colors across the light strip, so I'm assuming it must be possible.

**Pull request merged**
